[package]
name = "elanmoc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
elanmoc-usb.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["signal"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
